name: ulearning_app
description: "A Bloc State Management"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  dots_indicator: ^3.0.0
  intl: ^0.18.1
  cloud_firestore: ^4.13.3
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  fluttertoast: ^8.2.2
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  flutter_easyloading: ^3.0.5
  dio: ^5.4.0
  webview_flutter: ^4.8.0
  video_player: ^2.9.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/animation/
